"""根据用户信息生成 PDF 简历（用于 MCP 引导填写后自动上传）。"""

from __future__ import annotations

import os
import tempfile
from datetime import datetime
from pathlib import Path


def _pick_cjk_font() -> str | None:
    candidates = [
        os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts", "simhei.ttf"),
        os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts", "msyh.ttc"),
        os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts", "simsun.ttc"),
        "/System/Library/Fonts/PingFang.ttc",
        "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    return None


def build_resume_pdf(
    *,
    name: str,
    phone: str = "",
    sex: str = "",
    birthday: str = "",
    city: str = "",
    intention_address: str = "",
    salary_expectation: str = "",
    skills: list[str] | None = None,
    work_experience: str = "",
    self_intro: str = "",
    education: str = "",
) -> Path:
    try:
        from fpdf import FPDF
    except ImportError as e:
        raise ValueError("缺少 fpdf2 依赖，请执行: pip install fpdf2") from e

    if not name.strip():
        raise ValueError("生成简历至少需要姓名")

    font_path = _pick_cjk_font()
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(15, 15, 15)
    pdf.add_page()
    width = pdf.epw

    if font_path:
        pdf.add_font("CJK", "", font_path)
        pdf.set_font("CJK", size=16)
    else:
        pdf.set_font("Helvetica", size=16)

    pdf.multi_cell(width, 12, "个人简历", align="C")
    pdf.ln(4)

    body_size = 12 if font_path else 11
    if font_path:
        pdf.set_font("CJK", size=body_size)
    else:
        pdf.set_font("Helvetica", size=body_size)

    def line(label: str, value: str):
        if value:
            pdf.multi_cell(width, 8, f"{label}：{value}")

    line("姓名", name.strip())
    line("性别", sex.strip())
    line("出生年月", birthday.strip())
    line("手机", phone.strip())
    line("意向城市", city.strip())
    line("意向工作地址", intention_address.strip())
    line("期望薪资", salary_expectation.strip())
    if skills:
        line("技能标签", "、".join(skills))
    if education.strip():
        pdf.ln(2)
        pdf.multi_cell(width, 8, "教育背景：")
        pdf.multi_cell(width, 8, education.strip())
    if work_experience.strip():
        pdf.ln(2)
        pdf.multi_cell(width, 8, "工作经历：")
        pdf.multi_cell(width, 8, work_experience.strip())
    if self_intro.strip():
        pdf.ln(2)
        pdf.multi_cell(width, 8, "自我评价：")
        pdf.multi_cell(width, 8, self_intro.strip())

    pdf.ln(4)
    pdf.set_font("Helvetica", size=9)
    pdf.multi_cell(width, 8, f"Generated by youhuo-c-api · {datetime.now():%Y-%m-%d %H:%M}")

    safe_name = "".join(ch for ch in name.strip() if ch.isalnum() or "\u4e00" <= ch <= "\u9fff") or "resume"
    out_dir = Path(tempfile.gettempdir()) / "youhuo-resumes"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{safe_name}_简历.pdf"
    pdf.output(str(out_path))
    return out_path


RESUME_FORM_GUIDE = """
请提供以下信息，我将为你生成 PDF 简历并上传到有活平台：

必填：
- name：姓名
- phone：手机号

建议填写：
- sex：性别
- birthday：出生年月（如 199001）
- city / intention_address：意向城市与地址
- salary_expectation：期望薪资（如 15-20元/时）
- skills：技能标签，逗号分隔（如 服务员,传菜员）
- education：教育背景
- work_experience：工作经历
- self_intro：自我评价

也可直接提供已有文件路径，调用 manage_resume(action=\"upload\", file_path=...) 上传 pdf/doc/docx。
""".strip()
